### ISSUE TITLE
Bug in object enumeration benchmark

### ISSUE THREAD

**Issue by bergus** [davidmarkclements/v8-perf#22] opened 2017-08-12 18:38 UTC
```js
// object-iteration.js
  for (var prop in obj) {
    if (obj.hasOwnProperty(prop)) {
```
doesn't work with objects that have a custom `hasOwnProperty` property. In fact, [I argue that it shouldn't be necessary at all](https://stackoverflow.com/a/45014721/1048572).
It's a wild guess, but I could even imagine this to be the reason for the drastic regression - what if not `for in`, but `hasOwnProperty` is the thing that became slower?

I would suggest replacing that test case of the property enumeration benchmark with the following two variants:
```js
suite.add('plain for-in', function() {
  var obj = {
    x: 1,
    y: 1,
    z: 1
  }
  var total = 0
  for (var prop in obj) {
    total += obj[prop]
  }
})
suite.add('for-in with inheritance safeguard', function() {
  var obj = {
    x: 1,
    y: 1,
    z: 1
  }
  var hasOwnProperty = Object.prototype.hasOwnProperty
  var total = 0
  for (var prop in obj) {
    if (hasOwnProperty.call(obj, prop)) {
      total += obj[prop]
    }
  }
})
```

**Comment by davidmarkclements** [comment] 2017-08-12 21:07
Yep I understand where your coming from - i would argue it's not a bug to use hasOwnProperty directly since, from a development philosophy, inputs should be cleaned (e.g json validation) prior to this loop. However a more defensive philosophy would take your approach, but at the cost of using `.call`.  

On the other hand not checking for own property introduces further expectations about the object being looped over - something we considered for the post but decided not to get into to

Closing for now, but if you'd like to submit a PR with all three scenarios, run the benchmarks, edit the spreadsheet with the additional results, generate the graphs, and then alter the blog post write up I'll be happy to accept - and we'll attribute the adjustment to you

**Closed by davidmarkclements** 2017-08-12 21:07 UTC

**Comment by bergus** [comment] 2017-08-14 16:47
Sorry, I don't have all the node versions available here, and it would be better to run all the benchmarks on the same machine. I would have guessed you already have the tooling set up (or did you do everything manually?), so if you can check whether the results for the other loops differ I'll be happy to update the graphs and the blog post edit.
